# I. Creating PCA function from scratch

Before you begin this tutorial, I would recommend you spend some time on this paper.
https://arxiv.org/pdf/1404.1100

It is a great paper by Jon Shlens!

In [1]:
import numpy as np
import pandas as pd
#np.set_printoptions(precision=8) #to set precision if needed


#Function for finding PCA 
def pca_func(X):
    '''
    This function takes an array of n*m matrix where m is the type of data and n is the number of data points
    and output the eigen vectors, eigen values and transformed data using the PCA method
    '''
    #calling standardize function to make data normalized with 0 mean
    X=standardize(X)

    n, m = X.shape
    # Compute covariance matrix
    C = np.dot(X.T, X) / (n-1)
    # Eigen decomposition
    eigen_vals, eigen_vecs = np.linalg.eig(C)
    # Project X onto PC space
    X_pca = np.dot(X, eigen_vecs)
    return eigen_vecs,eigen_vals,X_pca


#Function for standardization
def standardize(X):                       # X is the input data
    mu=sum(X)/len(X)                      # Mean across columns
    var=sum((X-mu)**2)/len(X)             #Variance of the data
    z=(X-mu)/(var**0.5)                   #Normalization
    return z

# Data for understanding the concept

First data will contain the length, breadth and height of the cube. We all know that they are equal and hence only one column is sufficient to represent the data. PCA and SVD just extract this feature.

Second data will be about speed(m/s) , distance covered(m) and time(in seconds).We will assume that we don't know the relationship between speed, time and distance (but actuaaly we do). In this, we know that two columns should be sufficient to represent the entire data. PCA and SVD will just show this.



# 1. Understanding Cube dataset

In [2]:
#Input Data for Cube


X=np.array([
    [2,2,2],
    [4,4,4],
    [1,1,1],
    [0.2,0.2,0.2],
    [5,5,5],
    [100,100,100],
    [9,9,9]
]
)

E,eigen_values,Y=pca_func(X)
P=E.T
print("Principal vectors\n", P)

Principal vectors
 [[ 5.77350269e-01  5.77350269e-01  5.77350269e-01]
 [-4.43374929e-17 -7.07106781e-01  7.07106781e-01]
 [ 8.16184513e-01 -4.27640407e-01 -3.88544106e-01]]


## Transformed data

In [3]:
print("Transformed data Y\n",Y)

Transformed data Y
 [[-7.83227402e-01  2.58333199e-17  6.97948461e-17]
 [-6.80940241e-01  5.70806499e-17  5.35883500e-17]
 [-8.34370982e-01  2.98358107e-17  6.71138288e-17]
 [-8.75285846e-01  4.73918015e-17  1.02589412e-16]
 [-6.29796661e-01  5.30781591e-17  5.62693673e-17]
 [ 4.22884347e+00 -2.50287937e-16 -2.49815787e-16]
 [-4.25222339e-01  2.77555756e-17  4.16333634e-17]]


## Variance

In [4]:
# Finding variance 
def variance(data):
    no_of_data=len(data)
    mu=np.sum(data,axis=0)/no_of_data               #mean across columns
    var=sum((data-mu)**2)/no_of_data
    var_explained=var/sum(var)
    return var,var_explained


In [5]:
print("Variance along principle direction for P. First array is variance and second is variance explained.\n")
print(variance(E))

Variance along principle direction for P. First array is variance and second is variance explained.

(array([8.21730110e-33, 3.33333333e-01, 3.33333333e-01]), array([1.23259516e-32, 5.00000000e-01, 5.00000000e-01]))


In [6]:
print("Variance in the transformed data \n")
print(variance(Y))

Variance in the transformed data 

(array([3.00000000e+00, 1.04687207e-32, 1.24617513e-32]), array([1.00000000e+00, 3.48957355e-33, 4.15391711e-33]))


## II. PCA using sklearn

In [7]:
from sklearn.decomposition import PCA
X_standard=standardize(X)                 #standardizing data before use
pca = PCA(n_components=3)
x=pca.fit(X_standard)
print("Variance explained\n",pca.explained_variance_ratio_)
print("\nP matrix using sklearn PCA\n",pca.components_)

#printing transformed data from sklearn
print("\nTransformed data usign sklearn PCA\n")
print(pca.transform(X_standard))
print("\nComparison of this transformed data with that of direct PCA function\n")
print(pca.transform(X_standard)-Y)

Variance explained
 [1.00000000e+00 5.10610875e-32 1.09958905e-63]

P matrix using sklearn PCA
 [[ 0.57735027  0.57735027  0.57735027]
 [-0.81649658  0.40824829  0.40824829]
 [-0.          0.70710678 -0.70710678]]

Transformed data usign sklearn PCA

[[-7.83227402e-01 -8.17702297e-17  2.43705824e-17]
 [-6.80940241e-01 -5.82322590e-17  4.20779239e-17]
 [-8.34370982e-01 -9.60858366e-17  7.91574827e-17]
 [-8.75285846e-01 -8.43152130e-17  6.42240838e-17]
 [-6.29796661e-01 -4.39166521e-17  4.28021748e-17]
 [ 4.22884347e+00  2.95463264e-16 -2.42820275e-16]
 [-4.25222339e-01 -4.16333634e-17  2.77555756e-17]]

Comparison of this transformed data with that of direct PCA function

[[-1.11022302e-16 -1.07603550e-16 -4.54242637e-17]
 [-1.11022302e-16 -1.15312909e-16 -1.15104261e-17]
 [-1.11022302e-16 -1.25921647e-16  1.20436539e-17]
 [-1.11022302e-16 -1.31707015e-16 -3.83653281e-17]
 [ 0.00000000e+00 -9.69948112e-17 -1.34671926e-17]
 [ 0.00000000e+00  5.45751201e-16  6.99551233e-18]
 [-5.55111512e

### Explanation for PCA
This function is almost similar to the the function described above. Matrix P is the transpose of Eigen vector.

We can see that alomst 100% of the variance is explained by just the first column (first Principal Component).
Also, comparison of data can be tricky in other cases as the inbuilt function arranged the PCs in the order of decreasing importance (variance explained). In this case, as it is only one that is main; that need not be checked!

## III.SVD using numpy

In [8]:
n,m=X.shape

from numpy.linalg import svd 
U, S, Vt = svd(X_standard, full_matrices=True)
Sigma = np.zeros((n, m), dtype=float)
Sigma[:m, :m] = np.diag(S)
print("Transformed data using numpy SVD \nX_svd= U * Sigma\n ")
X_svd=np.dot(U, Sigma)
print(X_svd)

print("\nComparison of this transformed data with that of direct PCA function\n")
print(X_svd-Y)

print("\nVariance Explained")
print(variance(X_svd))

Transformed data using numpy SVD 
X_svd= U * Sigma
 
[[-7.83227402e-01 -1.01898173e-15  1.01092274e-34]
 [-6.80940241e-01  3.05298860e-17  1.49771214e-31]
 [-8.34370982e-01 -1.36562109e-17  6.46928446e-33]
 [-8.75285846e-01  2.30241171e-17 -2.64395044e-33]
 [-6.29796661e-01  1.35623235e-17 -4.97835079e-33]
 [ 4.22884347e+00 -1.79148590e-16  2.35617576e-32]
 [-4.25222339e-01  5.67749558e-18 -5.58216822e-33]]

Comparison of this transformed data with that of direct PCA function

[[ 1.88737914e-15 -1.04481505e-15 -6.97948461e-17]
 [ 2.22044605e-16 -2.65507638e-17 -5.35883500e-17]
 [ 2.22044605e-16 -4.34920216e-17 -6.71138288e-17]
 [ 3.33066907e-16 -2.43676845e-17 -1.02589412e-16]
 [ 2.22044605e-16 -3.95158356e-17 -5.62693673e-17]
 [-1.77635684e-15  7.11393469e-17  2.49815787e-16]
 [ 1.11022302e-16 -2.20780800e-17 -4.16333634e-17]]

Variance Explained
(array([3.00000000e+00, 1.26707663e-31, 2.73165457e-63]), array([1.00000000e+00, 4.22358875e-32, 9.10551522e-64]))


### Explanation
This also gives the same result.

## Accuracy

In all the three method we see that variance explained is almost 100% for only 1 PC. Only one column is sufficient to represent the side of the cube.

# 2. Understanding random data of speed, distance and time

In [9]:
#Input Data for Cube
#distance is in first column, time in 2nd column and speed in 3rd.

X=np.array([
    [1,2,0.5],
    [40,10,4],
    [1,1,1],
    [0.2,0.1,2],
    [500,5,100],
    [100,20,5],
    [9,9,1]
]
)

E,eigen_values,Y=pca_func(X)
P=E.T
print("Principal vectors\n", P)

print("\nTransformed data Y\n",Y)

Principal vectors
 [[-0.70327211  0.10611967  0.70295587]
 [ 0.70726305  0.00426342  0.70693762]
 [-0.07202299 -0.99434423  0.07805287]]

Transformed data Y
 [[-1.81847814e-02 -7.11561189e-01  7.28675220e-01]
 [ 2.28274129e-02 -4.71300812e-01 -5.07166800e-01]
 [-2.42918290e-02 -7.01895851e-01  8.83221039e-01]
 [-1.51773770e-02 -6.85179835e-01  1.02390596e+00]
 [ 3.21008836e-03  3.42690255e+00  2.83234488e-01]
 [-4.18741313e-02 -1.93712932e-01 -2.06444317e+00]
 [ 7.34906174e-02 -6.63251929e-01 -3.47426738e-01]]


In [10]:
# Finding variance 
def variance(data):
    no_of_data=len(data)
    mu=np.sum(data,axis=0)/no_of_data               #mean across columns
    var=sum((data-mu)**2)/no_of_data
    var_explained=var/sum(var)
    return var,var_explained
print("Variance in the transformed data \n")
print(variance(Y))

Variance in the transformed data 

(array([1.26240588e-03, 1.98738027e+00, 1.01135733e+00]), array([4.20801960e-04, 6.62460089e-01, 3.37119109e-01]))


## II. PCA using sklearn

In [11]:
from sklearn.decomposition import PCA
X_standard=standardize(X)                 #standardizing data before use
pca = PCA(n_components=3)
x=pca.fit(X_standard)
print("Variance explained\n",pca.explained_variance_ratio_)
print("\nP matrix using sklearn PCA\n",pca.components_)

#printing transformed data from sklearn
print("\nTransformed data usign sklearn PCA\n")
print(pca.transform(X_standard))

Variance explained
 [6.62460089e-01 3.37119109e-01 4.20801960e-04]

P matrix using sklearn PCA
 [[ 0.70726305  0.00426342  0.70693762]
 [ 0.07202299  0.99434423 -0.07805287]
 [-0.70327211  0.10611967  0.70295587]]

Transformed data usign sklearn PCA

[[-7.11561189e-01 -7.28675220e-01 -1.81847814e-02]
 [-4.71300812e-01  5.07166800e-01  2.28274129e-02]
 [-7.01895851e-01 -8.83221039e-01 -2.42918290e-02]
 [-6.85179835e-01 -1.02390596e+00 -1.51773770e-02]
 [ 3.42690255e+00 -2.83234488e-01  3.21008836e-03]
 [-1.93712932e-01  2.06444317e+00 -4.18741313e-02]
 [-6.63251929e-01  3.47426738e-01  7.34906174e-02]]


## SVD using numpy

In [12]:
n,m=X.shape

from numpy.linalg import svd 
U, S, Vt = svd(X_standard, full_matrices=True)
Sigma = np.zeros((n, m), dtype=float)
Sigma[:m, :m] = np.diag(S)
print("Transformed data using numpy SVD \nX_svd= U * Sigma\n ")
X_svd=np.dot(U, Sigma)
print(X_svd)

print("\nVariance Explained")
print(variance(X_svd))

Transformed data using numpy SVD 
X_svd= U * Sigma
 
[[-7.11561189e-01 -7.28675220e-01 -1.81847814e-02]
 [-4.71300812e-01  5.07166800e-01  2.28274129e-02]
 [-7.01895851e-01 -8.83221039e-01 -2.42918290e-02]
 [-6.85179835e-01 -1.02390596e+00 -1.51773770e-02]
 [ 3.42690255e+00 -2.83234488e-01  3.21008836e-03]
 [-1.93712932e-01  2.06444317e+00 -4.18741313e-02]
 [-6.63251929e-01  3.47426738e-01  7.34906174e-02]]

Variance Explained
(array([1.98738027e+00, 1.01135733e+00, 1.26240588e-03]), array([6.62460089e-01, 3.37119109e-01, 4.20801960e-04]))


## Explanation 
Here, we can see that PC1 can explain 66.25% of data while PC2 can explain 33.72% of data. Two of them are close to 100%.

# Note
It is important to note that all these data are random and it actually doesn't make sense to use PCA and SVD to modify the data as we already have the raw data and it can explain the info much more accurately and it is easy to explain.